# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelist',
            name='expendtime',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
