# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0002_activelist_expendtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activelist',
            old_name='user',
            new_name='username',
        ),
    ]
