# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0003_auto_20170109_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelist',
            name='datetime',
            field=models.DateField(),
        ),
    ]
