# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0004_auto_20170110_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectl', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activelist',
            options={'ordering': ['datetime']},
        ),
        migrations.RenameField(
            model_name='activelist',
            old_name='upype',
            new_name='utype',
        ),
        migrations.AlterField(
            model_name='activelist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activelist.Client'),
        ),
        migrations.AlterField(
            model_name='activelist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activelist.Project'),
        ),
    ]
