# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0005_auto_20170112_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientl',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectl',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
