# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activelist', '0007_auto_20170118_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activelist',
            options={'ordering': ['-datetime']},
        ),
    ]
